##################
# settings
##################
event_name: April Fool's Day

default_gimmick_chance: 0.67

mergeable:
    default:
        1:
            # Let Pokemon target themselves with attacks (only relevant for doubles)
            always_allow_self_target: True
            pbr:
                custom_iso: 'muted-announcer'
                iso_language: 'english'
                custom_announcer: 'pbr-multilingual'
                #custom_announcer: 'pbr-and-stadium2-co-announcers'
            effectiveness: 'ice-se-on-bug'
            inputless_random_switch_chance: 0
        3:
            team_sizes:
                !!python/tuple [1,6]:
                    rarity: 0.0
                    biddable: yes
                !!python/tuple [2,6]:
                    rarity: 0.0
                    biddable: yes
                !!python/tuple [3,6]:
                    rarity: 0.0
                    biddable: yes
                !!python/tuple [4,6]:
                    rarity: 0.0
                    biddable: yes
                !!python/tuple [5,6]:
                    rarity: 0.2
                    biddable: yes
                !!python/tuple [6,6]:
                    rarity: 0.4
                    biddable: yes

                !!python/tuple [1,5]:
                    rarity: 0.0
                    biddable: yes
                !!python/tuple [2,5]:
                    rarity: 0.0
                    biddable: yes
                !!python/tuple [3,5]:
                    rarity: 0.0
                    biddable: yes
                !!python/tuple [4,5]:
                    rarity: 0.3
                    biddable: yes
                !!python/tuple [5,5]:
                    rarity: 0.6
                    biddable: yes

                !!python/tuple [1,4]:
                    rarity: 0.0
                    biddable: yes
                !!python/tuple [2,4]:
                    rarity: 0.0
                    biddable: yes
                !!python/tuple [3,4]:
                    rarity: 0.2
                    biddable: yes
                !!python/tuple [4,4]:
                    rarity: 1.0
                    biddable: yes

                !!python/tuple [1,3]:
                    rarity: 0.0
                    biddable: yes
                !!python/tuple [2,3]:
                    rarity: 0.0
                    biddable: yes
                !!python/tuple [3,3]:
                    rarity: 1.3
                    biddable: yes

                !!python/tuple [1,2]:
                    rarity: 0.0
                    biddable: yes
                !!python/tuple [2,2]:
                    rarity: 0.2
                    biddable: yes

                !!python/tuple [1,1]:
                    rarity: 0.1
                    biddable: yes

################
metagames:
################
    #########
    base:
    #########
        # Rarities are not percentages.
        # Modes are selected by accumulating and then randomly bisecting their rarities.
        simple:       {rarity: 30.0}
        advanced:     {rarity: 10.0}
        pwt:
            rarity:  4.0
            match_settings:
                2:
                    pbr:
                        custom_iso: 'muted-announcer'
                        iso_language: 'english'
                        custom_announcer: 'pbr-multilingual'
        ubers:        {rarity:  1.5}
        dubers:
            rarity:  3.0
            gimmick_rarity_whitelist:
                - doubles
                - doubles_inputting_combo_of_2
                - doubles_inputting_combo_of_3
                - doubles_inputting_combo_of_4
                - doubles_defiance_combo_of_2
                - doubles_defiance_combo_of_3
                - doubles_defiance_combo_of_4
        middle_cup:   {rarity:  2.5}
        little_cup:   {rarity:  2.5}
        stadium2:
            rarity:  2.5
            gimmick_rarity_whitelist:
                - s2_defiance_and_random_order
            gimmick_rarities:
                 s2_defiance_and_random_order: 1.0
            match_settings:
                2:
                    pbr:
                        custom_announcer: 'pbr-and-stadium2-co-announcers'
        runmons:
            rarity:  1.5
            gimmick_rarity_whitelist:
                - defiance
        anime:        {rarity:  1.5}
        manga:        {rarity:  1.5}
        pbr_gold:     {rarity:  0.5}
        metronome:    {rarity:  0.4}
        ohko:         {rarity:  0.02}
        seismic_toss: {rarity:  0.0}
        kapow:        {rarity:  0.0}
        rough_skin:   {rarity:  0.0}
#        input_war:    {rarity:  0.0}
        type_warfare: {rarity:  1.5}
        color_clash:  {rarity:  1.5}
        starters:     {rarity:  0.0}

        halloween:
            rarity: 2.0
            match_settings:
                2:
                    pbr:
                        custom_iso: 'muted-announcer'
                        iso_language: 'english'
                        custom_announcer: 'pbr-halloween'
        apokelypse:
            rarity: 1.0
            match_settings:
                2:
                    pbr:
                        custom_iso: 'muted-announcer'
                        iso_language: 'english'
                        custom_announcer: 'pbr-halloween'
        costume:
            rarity:  2.5
        nightmare:
            rarity:  0.0
            match_settings:
                2:
                    pbr:
                        custom_iso: 'muted-announcer'
                        iso_language: 'english'
                        custom_announcer: 'pbr-halloween'
        shadow_force:
            rarity:  0.0
            match_settings:
                2:
                    pbr:
                        custom_iso: 'muted-announcer'
                        iso_language: 'english'
                        custom_announcer: 'pbr-halloween'
        astonish:
            rarity:  0.0
            match_settings:
                2:
                    pbr:
                        custom_iso: 'muted-announcer'
                        iso_language: 'english'
                        custom_announcer: 'pbr-halloween'

        christmas:          {rarity:  2.0}
        christmas_green:    {rarity:  2.0}
        dinner:             {rarity:  1.0}
        nuclear_winter:     {rarity:  1.5}
        new_year:           {rarity:  1.5}
        present:            {rarity:  0.0}
        snowball:           {rarity:  0.0}

    #########
    versus_mixes:
    #########
        vs_mix:       {rarity: 1.0}

    #########
    random_mixes:
    #########
        random_mix_auto: {rarity: 2.5}
        random_mix_bid:  {rarity: 0.0}
        random_mix_bid2: {rarity: 0.0}
        random_mix_bid3: {rarity: 0.0}
        luckmons:        {rarity: 0.0}
        random_mix_all_bid:
            # Allow token match bids for all metagames.
            sub_modes:
              - simple
              - advanced
              - pwt
              - ubers
              - dubers
              - middle_cup
              - little_cup
              - stadium2
              - runmons
              - anime
              - manga
              - pbr_gold
              - metronome
              - ohko
              - halloween
              - apokelypse
              - costume
              - nightmare
              - shadow_force
              - astonish
              - christmas
              - dinner
              - nuclear_winter
              - new_year
              - present
              - snowball
            display_name: Mix
            icon_id: mix
            description: # Leave blank for auto generated description.


################
gimmicks:
################
    #########
    base:
    #########
        # input change
        defiance:
          rarity: 3.0
          match_settings:
              2:
                  ally_hit:
                      100: 10
                      50: 10
                      33: 10
                      25: 10
                      10: 10
                      0: 30
        duel:           {rarity: 1.5}
        sync5050:       {rarity: 1.0}
        # team change
        random_order:   {rarity: 1.0}
        secrecy:        {rarity: 1.0}
        traitor:        {rarity: 1.0}
        blind_bet:      {rarity: 0.6}
        # battle change
        doubles:
            match_settings:
                4:
                    team_sizes:
                        !!python/tuple [2,6]:
                            rarity: 0.0
                            biddable: yes
                        !!python/tuple [3,6]:
                            rarity: 0.0
                            biddable: yes
                        !!python/tuple [4,6]:
                            rarity: 0.0
                            biddable: yes
                        !!python/tuple [5,6]:
                            rarity: 0.5
                            biddable: yes
                        !!python/tuple [6,6]:
                            rarity: 1.0
                            biddable: yes

                        !!python/tuple [2,5]:
                            rarity: 0.0
                            biddable: yes
                        !!python/tuple [3,5]:
                            rarity: 0.0
                            biddable: yes
                        !!python/tuple [4,5]:
                            rarity: 0.5
                            biddable: yes
                        !!python/tuple [5,5]:
                            rarity: 1.2
                            biddable: yes

                        !!python/tuple [2,4]:
                            rarity: 0.0
                            biddable: yes
                        !!python/tuple [3,4]:
                            rarity: 0.1
                            biddable: yes
                        !!python/tuple [4,4]:
                            rarity: 0.8
                            biddable: yes

                        !!python/tuple [2,3]:
                            rarity: 0.02
                            biddable: yes
                        !!python/tuple [3,3]:
                            rarity: 0.25
                            biddable: yes

                        !!python/tuple [2,2]:
                            rarity: 0.1
                            biddable: yes
            rarity: 7.0

        commitment:     {rarity: 1.0}
        sticky_inputs:  {rarity: 1.0}
        inverse:
            rarity: 2.0
            match_settings:
                2:
                    pbr:
                        custom_iso: 'muted-announcer'
                        iso_language: 'english'
                        custom_announcer: 'pbr-reverse'
                7:
                    effectiveness: 'inverse-of-ice-se-on-bug'
        fog:            {rarity: 25.0}
        speed:          {rarity: 50.0}
        fragile:        {rarity: 1.0}
        80_perc_hp:     {rarity: 0.5}
        afflicted:      {rarity: 0.5}
        timed:
            rarity: 4.0
            match_settings:
                1:
                    battle_timer: random
        defeatist:      {rarity: 7.0}
        german:         {rarity: 0.125}
        french:         {rarity: 0.125}
        spanish:        {rarity: 0.125}
        italian:        {rarity: 0.125}
        japanese:       {rarity: 0.125}
        # x-replace
        pinpoint:       {rarity: 1.0}
        chameleon:      {rarity: 1.0}
        shield:         {rarity: 0.2}
        armor:          {rarity: 0.2}
        adaptable:      {rarity: 0.5}
        explosive:      {rarity: 1.0}
        rainbow:        {rarity: 0.5}
        hit_and_run:    {rarity: 0.5}
        hidden_ace:     {rarity: 0.4}
        letdown:        {rarity: 0.1}
        fire_and_ice:   {rarity: 0.2}
        sky_battle:     {rarity: 0.5}
        rngod:
            rarity: 4.0
            match_settings:
              2:
                  pbr:
                      custom_iso: 'muted-announcer'
                      iso_language: 'english'
                      custom_announcer: 'pbr-random'
        clone:          {rarity: 1.0}
        sketchy:        {rarity: 0.4}
        lucky:          {rarity: 0.3}
        boing:          {rarity: 0.1}
        acid_rain:      {rarity: 1.0}
#        dev2:           {rarity: 0.0}

    #########
    random_combos:
    #########
        s2_defiance_and_random_order:   {rarity: 0.0}
        defiance_rngod:                 {rarity: 1.0}
        singles_combo_of_2:             {rarity: 3.0}
        singles_combo_of_3:             {rarity: 0.3}
        singles_combo_of_4:             {rarity: 0.05}
        # Doubles is separate, just for more precise control over the rarities
        doubles_inputting_combo_of_2:   {rarity: 1.5}
        doubles_inputting_combo_of_3:   {rarity: 1.2}
        doubles_inputting_combo_of_4:   {rarity: 0.03}
        doubles_defiance_combo_of_2:    {rarity: 7.0}
        doubles_defiance_combo_of_3:    {rarity: 5.0}
        doubles_defiance_combo_of_4:    {rarity: 0.5}
