mergeable:
  default:
      0:
        bet_bonus: 20
        switching_bet_bonus: 45

  multi_mode_ceilings:
      defiance_subset_exemptions:
          simple: 5
          advanced: 5
          runmons: 2
          stadium2: 5
          christmas: 2
          dinner: 2
          nuclear_winter: 2
          new_year: 2
          costume: 2
          metronome: 1
          rnggod: 2
          pwt: 2


##################
# settings
##################
event_name: DefianceProfitBonuses

default_gimmick_chance: 0.45

must_contain_all_gimmicks:
  - defiance

################
metagames:
################
    #########
    base:
    #########
        # Rarities are not percentages.
        # Modes are selected by accumulating and then randomly bisecting their rarities.
        simple:       {rarity: 30.0}
        advanced:     {rarity: 10.0}
        pwt:
            rarity:  4.0
            match_settings:
                2:
                    bet_bonus: 10
                    switching_bet_bonus: 20
        ubers:
            rarity:  1.5
            match_settings:
                2:
                    bet_bonus: 15
                    switching_bet_bonus: 30
        dubers:
            rarity:  3.0
            gimmick_rarity_whitelist:
                - doubles_defiance_combo_of_2
                - doubles_defiance_combo_of_3
                - doubles_defiance_combo_of_4
        middle_cup:   {rarity:  2.5}
        little_cup:   {rarity:  2.5}
        stadium2:
            rarity:  2.5
            gimmick_rarity_whitelist:
                - s2_defiance_and_random_order
            gimmick_rarities:
                s2_defiance_and_random_order: 1.0
            match_settings:
                2:
                    bet_bonus: 15
                    switching_bet_bonus: 30
        runmons:
            rarity:  1.5
            match_settings:
                2:
                    bet_bonus: 10
                    switching_bet_bonus: 20
        anime:
            rarity:  1.5
            match_settings:
                2:
                    bet_bonus: 10
                    switching_bet_bonus: 20
        manga:
            rarity:  1.5
            match_settings:
                2:
                    bet_bonus: 10
                    switching_bet_bonus: 20
        pbr_gold:     {rarity:  0.5}
        metronome:
            rarity:  0.4
            match_settings:
                5:
                    bet_bonus: 5
                    switching_bet_bonus: 5
        ohko:
            rarity:  0.02
            match_settings:
                5:
                    bet_bonus: 5
                    switching_bet_bonus: 5
        seismic_toss:
            rarity:  0.01
            match_settings:
                5:
                    bet_bonus: 5
                    switching_bet_bonus: 5
        kapow:
            rarity:  0.02
            match_settings:
                5:
                    bet_bonus: 5
                    switching_bet_bonus: 5
        rough_skin:
            rarity:  0.01
            match_settings:
                5:
                    bet_bonus: 5
                    switching_bet_bonus: 5

        type_warfare:
            rarity:  1.5
            match_settings:
                2:
                    bet_bonus: 15
                    switching_bet_bonus: 30
        color_clash:  {rarity:  1.5}
        starters:     {rarity:  0.0}

    #########
    versus_mixes:
    #########
        vs_mix:       {rarity: 1.0}

    #########
    random_mixes:
    #########
        random_mix_auto: {rarity: 2.5}
        random_mix_bid:  {rarity: 0.0}
        random_mix_bid2: {rarity: 0.0}
        random_mix_bid3: {rarity: 0.0}
        luckmons:
            rarity: 0.0
            match_settings:
                5:
                    bet_bonus: 5
                    switching_bet_bonus: 5


################
gimmicks:
################
    #########
    base:
    #########
        normal:         {}  # Must be present as a key to be present in the event
        # input change
        defiance:
            rarity: 1.0  # Rarity has no effect, see must_contain_any_gimmicks for details.
            match_settings:
                3:
                    bet_bonus: 10
        # team change
        random_order:
            rarity: 1.0
            match_settings:
                2:
                    bet_bonus: 35
                    switching_bet_bonus: 50
        secrecy:
            rarity: 1.0
            match_settings:
                3:
                    bet_bonus: 35
                    switching_bet_bonus: 50
        traitor:
            rarity: 1.0
            match_settings:
                3:
                    bet_bonus: 35
                    switching_bet_bonus: 50
        blind_bet:
            rarity: 0.6
            match_settings:
                3:
                    bet_bonus: 30
                    switching_bet_bonus: 45
        # battle change
        doubles:
            rarity: 6.0
            match_settings:
                2:
                    bet_bonus: 35
                    switching_bet_bonus: 50
        inverse:        {rarity: 2.0}
        fog:            {rarity: 1.4}
        speed:
            rarity: 2.0
            match_settings:
                1:
                    bet_bonus: 30
                    switching_bet_bonus: 45
        fragile:
            rarity: 1.0
            match_settings:
                3:
                    bet_bonus: 10
                    switching_bet_bonus: 20
        80_perc_hp:     {rarity: 0.5}
        afflicted:      {rarity: 0.5}
        defeatist:      {rarity: 5.0}
        timed:          {rarity: 1.0}
        german:         {rarity: 0.125}
        french:         {rarity: 0.125}
        spanish:        {rarity: 0.125}
        italian:        {rarity: 0.125}
        japanese:       {rarity: 0.125}
        # x-replace
        pinpoint:
            rarity: 1.0
            match_settings:
                1:
                    bet_bonus: 15
                    switching_bet_bonus: 30
        chameleon:      {rarity: 1.0}
        shield:         {rarity: 0.2}
        armor:          {rarity: 0.2}
        adaptable:
            rarity: 0.5
            match_settings:
                1:
                    bet_bonus: 15
                    switching_bet_bonus: 30
        explosive:
            rarity: 1.0
            match_settings:
                1:
                    bet_bonus: 15
                    switching_bet_bonus: 30
        rainbow:        {rarity: 0.5}
        hit_and_run:    {rarity: 0.5}
        hidden_ace:     {rarity: 0.4}
        letdown:        {rarity: 0.1}
        fire_and_ice:   {rarity: 0.2}
        sky_battle:     {rarity: 0.5}
        rngod:          {rarity: 0.6}
        clone:
            rarity: 1.0
            match_settings:
                1:
                    bet_bonus: 15
                    switching_bet_bonus: 30
        sketchy:
            rarity: 0.4
            match_settings:
                1:
                    bet_bonus: 15
                    switching_bet_bonus: 30
        lucky:          {rarity: 0.3}
        boing:          {rarity: 0.1}
        acid_rain:      {rarity: 1.0}
        hidden_bets:    {rarity: 5.0}

    #########
    random_combos:
    #########
        s2_defiance_and_random_order:    {rarity: 0.0}
        defiance_rngod:                  {rarity: 0.5}
        singles_combo_of_2:              {rarity: 3.0}
        singles_combo_of_3:              {rarity: 1.3}
        # Doubles is separate, just for more precise control over the rarities
        doubles_defiance_combo_of_2:     {rarity: 1.2}
        doubles_defiance_combo_of_3:     {rarity: 1.5}
        doubles_defiance_combo_of_4:     {rarity: 1.5}

##################
restrictions:
##################
    lift_restrictions:
      - [ubers, defiance]
      - [defiance, fog]
      - [defiance, letdown]