##################
# settings
##################
event_name: HalloweenProfit
default_metagame: halloween

mergeable:
  default:
      0:
        bet_bonus: 20
        switching_bet_bonus: 45


##################
metagames:
##################
    #########
    base:
    #########
        halloween:    {rarity: 30.0}
        apokelypse:
            rarity:  2.5
            match_settings:
                2:
                    bet_bonus: 15
                    switching_bet_bonus: 30
        costume:      {rarity:  2.5}
        metronome:
            rarity:  0.4
            set_tag: halloweenmetronome
            rarify_shinies: no
            match_settings:
                5:
                    bet_bonus: 5
                    switching_bet_bonus: 5
        nightmare:    {rarity:  0.02}
        shadow_force: {rarity:  0.02}
        astonish:     {rarity:  0.02}


##################
gimmicks:
##################
    #########
    base:
    #########
        normal: {}

        doubles:
            rarity: 6.0
            icon_id: hdoubles
            short_description: A battle between gruesome twosomes!
            description: A battle between gruesome twosomes!
            match_settings:
                2:
                    bet_bonus: 35
                    switching_bet_bonus: 50

        defiance:
            rarity: 3.0
            icon_id: hdefiance
            short_description: Ghosts defy inputs.
            description: These ghosts have no interest in your mortal instructions! They choose their own moves at random.
            match_settings:
                3:
                    bet_bonus: 10
      
        sync5050:
            rarity: 1.0
            icon_id: eyeball
            short_description: Input pools are fused by mad science!
            description: With the power of mad science, both teams have fused to share the same input pool 50-50.
            match_settings:
                3:
                    bet_bonus: 30
                    switching_bet_bonus: 45
       
        random_order:
            rarity: 1.0
            icon_id: hrandom_order
            short_description: Team ordering is randomized.
            description: Only the monsters themselves know the order in which they will appear on the battlefield...
            match_settings:
                2:
                    bet_bonus: 35
                    switching_bet_bonus: 50
     
        secrecy:
            rarity: 1.0
            icon_id: hsecrecy
            short_description: Each team has an invisible Pokémon.
            description: Ancient magicks hide one Pokémon from each team, only to be revealed once it is too late to bid...
            match_settings:
                3:
                    bet_bonus: 35
                    switching_bet_bonus: 50
       
        traitor:
            rarity: 1.0
            icon_id: htraitor
            short_description: Teams exchange two Pokémon.
            description: Ghosts have no need for mortal conceptions like loyalty- two will switch teams once the match begins.
            match_settings:
                3:
                    bet_bonus: 35
                    switching_bet_bonus: 50
   
        blind_bet:
            rarity: 0.6
            icon_id: bat
            short_description: The bettors are blind as bats!
            description: The bettors are blind as bats, unable to see the teams until the game begins.
            match_settings:
                3:
                    bet_bonus: 30
                    switching_bet_bonus: 45
   
        commitment:
            rarity: 2.0
            icon_id: hcommitment
            short_description: Only your first command can be heard.
            description: These brainless monsters will only listen to your first commands after betting has ended.
            match_settings:
                3:
                    bet_bonus: 10
                    switching_bet_bonus: 20

        sticky_inputs:
            rarity: 1.0
            # Icon's already a spider web.
            description: Only "-" input(s) can be changed. Your first mistake will surely be your last...
            match_settings:
                3:
                    bet_bonus: 10
                    switching_bet_bonus: 20

        inverse:
            rarity: 2.0
            icon_id: boo
            short_description: Type matchups are inverted.
            description: A trickster inverted the type matchups while you weren't looking! Immunities replaced by weaknesses.

        fog:
            rarity: 1.4
            icon_id: hauntedmansion
            short_description: Battle in deep, haunted fog.
            description: The battle takes place in a haunted colosseum, shrouded deep in fog.
    
        speed:
            rarity: 2.0
            icon_id: hspeed
            short_description: Change inputs quickly or perish.
            description: The battle is sped up. Time flies when you're fearing for your life...
            match_settings:
                1:
                    bet_bonus: 30
                    switching_bet_bonus: 45
     
        fragile:
            rarity: 1.0
            icon_id: hfragile
            short_description: All moves crumble after 1 use.
            description: These monsters only have enough energy left to use each move once.
            match_settings:
                3:
                    bet_bonus: 10
                    switching_bet_bonus: 20

        80_perc_hp:
            rarity: 0.5
            icon_id: h80_perc_hp
            short_description: "These Pokémon are already dying..."
            description: "These Pokémon are already dying... time to finish them off!"

        afflicted:
            rarity: 0.5
            icon_id: hgerm
            short_description: "Pokémon are seized by disease."
            description: "The Pokémon in this battle are afflicted with debilitating diseases."

        defeatist:      {rarity: 5.0}
        german:
            rarity: 0.125
            short_description: "Game plays in an unnatural tongue."
            description: "A nefarious spirit seizes the announcer, causing him to speak in unnatural tongues."

        french:
            rarity: 0.125
            short_description: "Game plays in an unnatural tongue."
            description: "A malicious spirit seizes the announcer, causing him to speak in unnatural tongues."

        spanish:
            rarity: 0.125
            short_description: "Game plays in an unnatural tongue."
            description: "A wicked spirit seizes the announcer, causing him to speak in unnatural tongues."

        italian:
            rarity: 0.125
            short_description: "Game plays in an unnatural tongue."
            description: "A vile spirit seizes the announcer, causing him to speak in unnatural tongues."

        japanese:
            rarity: 0.125
            short_description: "Game plays in an unnatural tongue."
            description: "A demonic spirit seizes the announcer, causing him to speak in unnatural tongues."

        departed:
            rarity: 1.0
        
        rngod:
            rarity: 0.6
            icon_id: frankenstein
            short_description: Pokémon are made of random parts.
            description: Pokémon hobbled together from random parts lurch into the arena.


        clone:
            rarity: 1.0
            icon_id: hclone
            species_replace:
                one_per_match: yes
                pool:
                  [Gastly, Haunter, Gengar, Misdreavus, Mismagius, Shuppet, Banette, Duskull, Dusclops, Dusknoir, Drifloon, Drifblim, Spiritomb, Giratina, Sableye, Froslass, Rotom]
            item_replace:
                pool:
                - Sticky Barb
                only_for_species:
                  [Giratina, Dusknoir]
            display_name: Clone
            short_description: Pokémon turn into spirits.
            description: The spirits of these Pokémon will fight in their place.
            match_settings:
                1:
                    bet_bonus: 15
                    switching_bet_bonus: 30

    #########
    random_combos:
    #########
        defiance_rngod:               {rarity: 2.0}
        singles_combo_of_2:           {rarity: 3.0}
        singles_combo_of_3:           {rarity: 1.3}
        singles_combo_of_4:           {rarity: 0.4}
        doubles_defiance_combo_of_2:  {rarity: 1.2}
        doubles_defiance_combo_of_3:  {rarity: 1.5}
        doubles_defiance_combo_of_4:  {rarity: 0.5}
        doubles_inputting_combo_of_2: {rarity: 1.4}
        doubles_inputting_combo_of_3: {rarity: 0.5}
        doubles_inputting_combo_of_4: {rarity: 0.1}
