##################
# settings
##################

event_name: Hidden

default_gimmick_chance: 0.45

must_contain_all_gimmicks:
    - hidden_bets


################################
bet_limits:
################################
    bet_limit_type: "bands"
    betting_start:
        limit:     # Set an amount if desired.
    after_betting_start:
        # Add entries if desired.
    before_betting_end:
        # Add or remove entries as desired.
      - seconds: 30
        limit: 5000

mergeable:
  default:
      0:
        bet_bonus: 15
        switching_bet_bonus: 30

  multi_mode_ceilings:
      defiance_subset_exemptions:
          simple: 8
          advanced: 8
          runmons: 3
          stadium2: 8
          christmas: 3
          dinner: 3
          nuclear_winter: 3
          new_year: 3
          costume: 3
          metronome: 2
          rnggod: 3
          pwt: 3


################
metagames:
################
    #########
    base:
    #########
        # Rarities are not percentages.
        # Modes are selected by accumulating and then randomly bisecting their rarities.
        simple:       {rarity: 30.0}
        advanced:     {rarity: 10.0}
        pwt:
            rarity:  4.0
            match_settings:
                2:
                    bet_bonus: 8
                    switching_bet_bonus: 15
            gimmick_rarities:
                hidden_bets: 1.0
        ubers:
            rarity:  1.5
            match_settings:
                2:
                    bet_bonus: 12
                    switching_bet_bonus: 23
        dubers:
            rarity:  3.0
            gimmick_rarity_whitelist:
                - doubles
                - doubles_inputting_combo_of_2
                - doubles_inputting_combo_of_3
                - doubles_defiance_combo_of_2
                - doubles_defiance_combo_of_3
        middle_cup:   {rarity:  2.5}
        little_cup:   {rarity:  2.5}
        stadium2:
            rarity:  2.5
            match_settings:
                2:
                    bet_bonus: 12
                    switching_bet_bonus: 23
            gimmick_rarity_whitelist:
                - s2_defiance_and_random_order
            gimmick_rarities:
                s2_defiance_and_random_order: 1.0
        runmons:
            rarity:  1.5
            match_settings:
                2:
                    bet_bonus: 8
                    switching_bet_bonus: 15
            gimmick_rarity_whitelist:
                - hidden_bets
        anime:
            rarity:  1.5
            match_settings:
                2:
                    bet_bonus: 8
                    switching_bet_bonus: 15
        manga:
            rarity:  1.5
            match_settings:
                2:
                    bet_bonus: 8
                    switching_bet_bonus: 15
        pbr_gold:     {rarity:  0.5}
        metronome:
            rarity:  0.4
            match_settings:
                5:
                    bet_bonus: 3
                    switching_bet_bonus: 3
        ohko:
            rarity:  0.02
            match_settings:
                5:
                    bet_bonus: 3
                    switching_bet_bonus: 3
        seismic_toss:
            rarity:  0.01
            match_settings:
                5:
                    bet_bonus: 3
                    switching_bet_bonus: 3
        kapow:
            rarity:  0.02
            match_settings:
                5:
                    bet_bonus: 3
                    switching_bet_bonus: 3
        rough_skin:
            rarity:  0.01
            match_settings:
                5:
                    bet_bonus: 3
                    switching_bet_bonus: 3

        input_war:
            rarity:  0.03
            match_settings:
                5:
                    bet_bonus: 3
                    switching_bet_bonus: 3
        type_warfare:
            rarity:  1.5
            match_settings:
                2:
                    bet_bonus: 12
                    switching_bet_bonus: 23
        color_clash:  {rarity:  1.5}
        starters:     {rarity:  0.0}

    #########
    versus_mixes:
    #########
        vs_mix:       {rarity: 1.0}

    #########
    random_mixes:
    #########
        random_mix_auto: {rarity: 2.5}
        random_mix_bid:  {rarity: 0.0}
        random_mix_bid2: {rarity: 0.0}
        random_mix_bid3: {rarity: 0.0}
        luckmons:
            rarity: 0.0
            match_settings:
                5:
                    bet_bonus: 3
                    switching_bet_bonus: 3


################
gimmicks:
################
    #########
    base:
    #########
        # input change
        defiance:
            rarity: 1.5
            match_settings:
                3:
                    bet_bonus: 8
        duel:           {rarity: 1.5}
        sync5050:
            rarity: 1.0
            match_settings:
                3:
                    bet_bonus: 23
                    switching_bet_bonus: 30
        # team change
        random_order:
            rarity: 1.0
            match_settings:
                2:
                    bet_bonus: 23
                    switching_bet_bonus: 30
        secrecy:
            rarity: 1.0
            match_settings:
                3:
                    bet_bonus: 23
                    switching_bet_bonus: 30
        traitor:
            rarity: 1.0
            match_settings:
                3:
                    bet_bonus: 23
                    switching_bet_bonus: 30
        blind_bet:
            rarity: 0.6
            match_settings:
                3:
                    bet_bonus: 23
                    switching_bet_bonus: 30
        # battle change
        doubles:        {rarity: 7.0}
        commitment:
            rarity: 1.0
            match_settings:
                3:
                    bet_bonus: 8
                    switching_bet_bonus: 15
        sticky_inputs:  {rarity: 1.0}
        inverse:        {rarity: 2.0}
        fog:            {rarity: 1.4}
        speed:
            rarity: 2.0
            match_settings:
                1:
                    bet_bonus: 23
                    switching_bet_bonus: 30
        fragile:
            rarity: 1.0
            match_settings:
                3:
                    bet_bonus: 8
                    switching_bet_bonus: 15
        80_perc_hp:     {rarity: 0.5}
        afflicted:      {rarity: 0.5}
        defeatist:      {rarity: 5.0}
        timed:          {rarity: 1.0}
        german:         {rarity: 0.125}
        french:         {rarity: 0.125}
        spanish:        {rarity: 0.125}
        italian:        {rarity: 0.125}
        japanese:       {rarity: 0.125}
        # x-replace
        pinpoint:
            rarity: 1.0
            match_settings:
                1:
                    bet_bonus: 12
                    switching_bet_bonus: 23
        chameleon:      {rarity: 1.0}
        shield:         {rarity: 0.2}
        armor:          {rarity: 0.2}
        adaptable:
            rarity: 0.5
            match_settings:
                1:
                    bet_bonus: 12
                    switching_bet_bonus: 23
        explosive:
            rarity: 1.0
            match_settings:
                1:
                    bet_bonus: 12
                    switching_bet_bonus: 23
        rainbow:        {rarity: 0.5}
        hit_and_run:    {rarity: 0.5}
        hidden_ace:     {rarity: 0.4}
        letdown:        {rarity: 0.1}
        fire_and_ice:   {rarity: 0.2}
        sky_battle:     {rarity: 0.5}
        rngod:          {rarity: 0.6}
        clone:
            rarity: 1.0
            match_settings:
                1:
                    bet_bonus: 12
                    switching_bet_bonus: 23
        sketchy:
            rarity: 0.4
            match_settings:
                1:
                    bet_bonus: 12
                    switching_bet_bonus: 23
        lucky:          {rarity: 0.3}
        boing:          {rarity: 0.1}
        acid_rain:      {rarity: 1.0}

        hidden_bets:    {rarity: 1}  # Rarity has no effect, see must_contain_any_gimmicks for details.

    #########
    random_combos:
    #########
        s2_defiance_and_random_order:    {rarity: 0.0}
        defiance_rngod:                  {rarity: 0.5}
        singles_combo_of_2:              {rarity: 3.0}
        singles_combo_of_3:              {rarity: 0.3}
        # Doubles is separate, just for more precise control over the rarities
        doubles_defiance_combo_of_2:     {rarity: 5.0}
        doubles_defiance_combo_of_3:     {rarity: 0.5}
        doubles_inputting_combo_of_2:    {rarity: 1.0}
        doubles_inputting_combo_of_3:    {rarity: 0.2}
